@PrismPackageRepo_HostAddress = http://localhost:8080

GET {{PrismPackageRepo_HostAddress}}/healthz
Accept: text/plain

###

GET {{PrismPackageRepo_HostAddress}}/api/v1/catalog
Accept: text/plain

###

GET {{PrismPackageRepo_HostAddress}}/api/v1/packages/hello/1.0.0/manifest
Accept: text/plain

###

GET {{PrismPackageRepo_HostAddress}}/api/v1/packages/hello/1.0.0/chunk?offset=0&length=64
Accept: application/octet-stream

###
